HIR_DEF(HIR)

HIR_DEF(Type)
HIR_DEF(FuncType)
HIR_DEF(NamedType)
HIR_DEF(PendingResolvedType)

HIR_DEF(Decl)

HIR_DEF(Value)
HIR_DEF(IntegerLiteral)
HIR_DEF(FloatLiteral)
HIR_DEF(Variant)
HIR_DEF(PrefixResult)
HIR_DEF(BinaryResult)
HIR_DEF(CallResult)
HIR_DEF(FuncValue)

HIR_DEF(Statement)
HIR_DEF(AssignStatement)
HIR_DEF(LoopStatement)
HIR_DEF(JumpStatement)
HIR_DEF(ReturnStatement)
HIR_DEF(BlockStatement)
HIR_DEF(BranchStatement)

#undef HIR_DEF